---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Synopsis {-#synopsis}


## Introduction {-}

1. What is SPC?
1. Preface
1. Synopsis

## Part 1: Understanding Variation {-}

1. Understanding Variation
1. Understanding SPC Charts
1. Looking for Signals
1. Charts Without Borders – using runs analysis as stand-alone rules with run charts
1. Using SPC in Healthcare

## Part 2: Constructing SPC Charts with R {-}

1. Your First SPC Charts with Base R
1. Calculating Control Limits
1. Highlighting Freaks, Shifts, and Trends
1. Core R Functions to Construct SPC Charts
1. SPC Charts with ggplot2
1. Introducing qicharts2

----

## Part 3: Case Studies and Worked Examples {-}

1. Case 1
1. Case 2
1. Case 3

## Part 4: Advanced SPC Techniques {-}

1. Screened I Chart (eliminating freak moving ranges before calculating limits)
1. SPC Charts for Rare Events
    - T Charts for Time Between Events
    - G Charts for Opportunities Between Cases
    - Bernoulli CUSUM charts for binary data
1. Dual charting
1. Prime Charts for Count Data with Very Large Subgroups
1. Improved (normalised) I chart
1. Funnel Plots for Categorical Subgroups
1. Pareto Charts for Ranking Problems

## Part 5: Best Practices and Tips {-}

1. Tips for Effective SPC Implementation
    - Automating production of SPC charts
    - Engaging stakeholders
    - Continuous monitoring and improvement.
    - Problems and challenges with SPC
1. Common Pitfalls to Avoid
    - Data issues, misinterpretation of charts
    - Overreacting to common cause variation (over-sensitive runs rules, too tight control limits)
    - Automating recalculation of control limits
    - One-to-one relation between PDSA cycles and dots on the plot
1. A Note on Rational Subgrouping and Sampling
1. When to Transform Data Before Plotting
1. High Volume Data
1. Scaling Up Charts (technical issues, tabular charts, grids)

## Part 6: Conclusion and Final Thoughts {-}

1. Summary of Key Points
    - jfældsajfsaækf
1. The Control Charts vs Run Charts Debate
1. Emerging trends in SPC and healthcare analytics
1. Encouragement for Continuous Learning and Application
1. Final Thoughts

## Appendices {-}

a. Included Data Sets
a. A Note on R
a. Basic Statistical Concepts
a. Diagnostic Properties of SPC Charts (Two Types of Errors When Using SPC)
a. Table of Critical Values for Longest Runs and Number of Crossings
a. Resources and Further Readings
a. Glossary of Terms

----

- Ideas for chapters / topics
    - Improved Runs Analysis Using the Bestbox and Cutbox approaches
    - CUSUM and EWMA Charts
    - Multivariate charts
    
----

- Ideas for papers:
  - RAGs to RICHes (two voices)
  - Big data issues -- CUSUM vs 3000 SPC charts
  - Improved I chart
  - The problem with SPC


