# What is Statistical Process Control {#what}

The ultimate purpose of collecting and analysing data is to support better decision-making and actions that will lead to improvement. Statistical Process Control (SPC) is a proven methodology for doing just that. 

SPC methodology provides a philosophy and framework for continually learning about the behaviour of processes for analytical purposes -- where the aim is to act on the underlying causes of variation to maintain or improve the performance of a process.  

SPC was initially developed by Walter A. Shewhart in the 1920s to improve the quality of manufactured products and has since been successfully used in many settings including healthcare.

At is core, SPC methodology involves the plotting of data over time to detect unusual patterns or variations that might indicate a change/problem with a process. This simple graphical device is underpinned by an intuitive theory of variation, the hypothesis-generating testing-cycle of the scientific method, and statistical theory. 

To understand SPC, we first need to understand the theory of variation on which it is based, which we demonstrate in the next chapter.