<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Calculating Control Limits | Mastering Statistical Process Control Charts in Healthcare</title>
  <meta name="description" content="This is a book (currently under early development) for data scientists about the practical application of statistical process control methodology in healthcare." />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Calculating Control Limits | Mastering Statistical Process Control Charts in Healthcare" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a book (currently under early development) for data scientists about the practical application of statistical process control methodology in healthcare." />
  <meta name="github-repo" content="anhoej/spc4hc" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Calculating Control Limits | Mastering Statistical Process Control Charts in Healthcare" />
  
  <meta name="twitter:description" content="This is a book (currently under early development) for data scientists about the practical application of statistical process control methodology in healthcare." />
  

<meta name="author" content="Jacob Anhøj &amp; Mohammed Amin Mohammed" />


<meta name="date" content="2024-09-11" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="first-chart.html"/>
<link rel="next" href="highlighting.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />



<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">
    Mastering SPC charts
  </a>
</li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Synopsis</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html#so-what-is-different-about-this-book"><i class="fa fa-check"></i>So what is different about this book?</a>
<ul>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html#prerequisites"><i class="fa fa-check"></i>Prerequisites</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html#how-to-use-this-book"><i class="fa fa-check"></i>How to use this book</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html#about-us"><i class="fa fa-check"></i>About us</a></li>
</ul></li>
<li class="part"><span><b>Part 1: Understanding Variation</b></span></li>
<li class="chapter" data-level="1" data-path="what.html"><a href="what.html"><i class="fa fa-check"></i><b>1</b> What is SPC</a></li>
<li class="chapter" data-level="2" data-path="variation.html"><a href="variation.html"><i class="fa fa-check"></i><b>2</b> Understanding Variation</a></li>
<li class="chapter" data-level="3" data-path="charts_intro.html"><a href="charts_intro.html"><i class="fa fa-check"></i><b>3</b> Introducing SPC Charts</a>
<ul>
<li class="chapter" data-level="3.1" data-path="charts_intro.html"><a href="charts_intro.html#anatomy-and-physiology-of-spc-charts"><i class="fa fa-check"></i><b>3.1</b> Anatomy and physiology of SPC charts</a></li>
<li class="chapter" data-level="3.2" data-path="charts_intro.html"><a href="charts_intro.html#some-common-types-of-control-charts-the-magnificient-seven"><i class="fa fa-check"></i><b>3.2</b> Some common types of control charts – The Magnificient Seven</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="charts_intro.html"><a href="charts_intro.html#counts"><i class="fa fa-check"></i><b>3.2.1</b> Counts</a></li>
<li class="chapter" data-level="3.2.2" data-path="charts_intro.html"><a href="charts_intro.html#measurements"><i class="fa fa-check"></i><b>3.2.2</b> Measurements</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="charts_intro.html"><a href="charts_intro.html#common-spc-charts-in-summary"><i class="fa fa-check"></i><b>3.3</b> Common SPC charts in summary</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="testing.html"><a href="testing.html"><i class="fa fa-check"></i><b>4</b> Testing for Special Cause Variation</a>
<ul>
<li class="chapter" data-level="4.1" data-path="testing.html"><a href="testing.html#patterns-of-non-random-variation-in-time-series-data"><i class="fa fa-check"></i><b>4.1</b> Patterns of non-random variation in time series data</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="testing.html"><a href="testing.html#freaks"><i class="fa fa-check"></i><b>4.1.1</b> Freaks</a></li>
<li class="chapter" data-level="4.1.2" data-path="testing.html"><a href="testing.html#shifts"><i class="fa fa-check"></i><b>4.1.2</b> Shifts</a></li>
<li class="chapter" data-level="4.1.3" data-path="testing.html"><a href="testing.html#trends"><i class="fa fa-check"></i><b>4.1.3</b> Trends</a></li>
<li class="chapter" data-level="4.1.4" data-path="testing.html"><a href="testing.html#other-unusual-patterns"><i class="fa fa-check"></i><b>4.1.4</b> Other unusual patterns</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="testing.html"><a href="testing.html#spc-rules"><i class="fa fa-check"></i><b>4.2</b> SPC rules</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="testing.html"><a href="testing.html#tests-based-on-sigma-limits"><i class="fa fa-check"></i><b>4.2.1</b> Tests based on sigma limits</a></li>
<li class="chapter" data-level="4.2.2" data-path="testing.html"><a href="testing.html#runs-analysis-tests-based-on-the-distribution-of-data-points-around-the-centre-line"><i class="fa fa-check"></i><b>4.2.2</b> Runs analysis – tests based on the distribution of data points around the centre line</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="testing.html"><a href="testing.html#charts-without-borders-using-runs-analysis-as-stand-alone-rules-with-run-charts"><i class="fa fa-check"></i><b>4.3</b> Charts without borders – using runs analysis as stand-alone rules with run charts</a></li>
<li class="chapter" data-level="4.4" data-path="testing.html"><a href="testing.html#a-practical-approach-to-spc-analysis"><i class="fa fa-check"></i><b>4.4</b> A practical approach to SPC analysis</a></li>
<li class="chapter" data-level="4.5" data-path="testing.html"><a href="testing.html#two-types-of-errors"><i class="fa fa-check"></i><b>4.5</b> Two types of errors when using SPC</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="responding.html"><a href="responding.html"><i class="fa fa-check"></i><b>5</b> Responding to SPC Signals</a></li>
<li class="part"><span><b>Part 2: Constructing SPC Charts</b></span></li>
<li class="chapter" data-level="6" data-path="first-chart.html"><a href="first-chart.html"><i class="fa fa-check"></i><b>6</b> Your First SPC Charts With Base R</a>
<ul>
<li class="chapter" data-level="6.1" data-path="first-chart.html"><a href="first-chart.html#a-run-chart-of-blood-pressure-data"><i class="fa fa-check"></i><b>6.1</b> A run chart of blood pressure data</a></li>
<li class="chapter" data-level="6.2" data-path="first-chart.html"><a href="first-chart.html#adding-control-limits-to-produce-a-control-chart"><i class="fa fa-check"></i><b>6.2</b> Adding control limits to produce a control chart</a></li>
<li class="chapter" data-level="6.3" data-path="first-chart.html"><a href="first-chart.html#thats-all-folks"><i class="fa fa-check"></i><b>6.3</b> That’s all, Folks!</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="limits.html"><a href="limits.html"><i class="fa fa-check"></i><b>7</b> Calculating Control Limits</a>
<ul>
<li class="chapter" data-level="7.1" data-path="limits.html"><a href="limits.html#introducing-the-spc-function"><i class="fa fa-check"></i><b>7.1</b> Introducing the spc() function</a></li>
<li class="chapter" data-level="7.2" data-path="limits.html"><a href="limits.html#count-data"><i class="fa fa-check"></i><b>7.2</b> Count data</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="limits.html"><a href="limits.html#c-chart"><i class="fa fa-check"></i><b>7.2.1</b> C chart</a></li>
<li class="chapter" data-level="7.2.2" data-path="limits.html"><a href="limits.html#u-chart"><i class="fa fa-check"></i><b>7.2.2</b> U chart</a></li>
<li class="chapter" data-level="7.2.3" data-path="limits.html"><a href="limits.html#p-chart"><i class="fa fa-check"></i><b>7.2.3</b> P chart</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="limits.html"><a href="limits.html#measurement-data"><i class="fa fa-check"></i><b>7.3</b> Measurement data</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="limits.html"><a href="limits.html#i-chart-aka-x-chart"><i class="fa fa-check"></i><b>7.3.1</b> I chart (aka X chart)</a></li>
<li class="chapter" data-level="7.3.2" data-path="limits.html"><a href="limits.html#mr-chart"><i class="fa fa-check"></i><b>7.3.2</b> MR chart</a></li>
<li class="chapter" data-level="7.3.3" data-path="limits.html"><a href="limits.html#x-bar-chart"><i class="fa fa-check"></i><b>7.3.3</b> X-bar chart</a></li>
<li class="chapter" data-level="7.3.4" data-path="limits.html"><a href="limits.html#s-chart"><i class="fa fa-check"></i><b>7.3.4</b> S chart</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="limits.html"><a href="limits.html#control-limits-in-short"><i class="fa fa-check"></i><b>7.4</b> Control limits in short</a></li>
<li class="chapter" data-level="" data-path="limits.html"><a href="limits.html#chart-constants"><i class="fa fa-check"></i>Control chart constants</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="highlighting.html"><a href="highlighting.html"><i class="fa fa-check"></i><b>8</b> Highlighting Freaks, Shifts, and Trends</a>
<ul>
<li class="chapter" data-level="8.1" data-path="highlighting.html"><a href="highlighting.html#introducing-the-cdiff-data-set"><i class="fa fa-check"></i><b>8.1</b> Introducing the cdiff data set</a></li>
<li class="chapter" data-level="8.2" data-path="highlighting.html"><a href="highlighting.html#improved-spc-function"><i class="fa fa-check"></i><b>8.2</b> Improved <code>spc()</code> function</a></li>
<li class="chapter" data-level="8.3" data-path="highlighting.html"><a href="highlighting.html#highlighting-special-cause-variation-in-short"><i class="fa fa-check"></i><b>8.3</b> Highlighting special cause variation in short</a></li>
<li class="chapter" data-level="" data-path="highlighting.html"><a href="highlighting.html#runs-analysis"><i class="fa fa-check"></i>Runs Analysis</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="r-functions.html"><a href="r-functions.html"><i class="fa fa-check"></i><b>9</b> One R Function to Rule Them All</a>
<ul>
<li class="chapter" data-level="9.1" data-path="r-functions.html"><a href="r-functions.html#examples"><i class="fa fa-check"></i><b>9.1</b> Examples</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="r-functions.html"><a href="r-functions.html#run-chart"><i class="fa fa-check"></i><b>9.1.1</b> Run chart</a></li>
<li class="chapter" data-level="9.1.2" data-path="r-functions.html"><a href="r-functions.html#i-and-mr-charts-for-individual-measurements"><i class="fa fa-check"></i><b>9.1.2</b> I and MR charts for individual measurements</a></li>
<li class="chapter" data-level="9.1.3" data-path="r-functions.html"><a href="r-functions.html#x-bar-and-s-charts-for-averages-and-standard-deviations-of-measurements"><i class="fa fa-check"></i><b>9.1.3</b> X-bar and S charts for averages and standard deviations of measurements</a></li>
<li class="chapter" data-level="9.1.4" data-path="r-functions.html"><a href="r-functions.html#c-and-u-charts-for-counts-and-rates"><i class="fa fa-check"></i><b>9.1.4</b> C and U charts for counts and rates</a></li>
<li class="chapter" data-level="9.1.5" data-path="r-functions.html"><a href="r-functions.html#p-chart-for-percentages"><i class="fa fa-check"></i><b>9.1.5</b> P chart for percentages</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="r-functions.html"><a href="r-functions.html#todo"><i class="fa fa-check"></i><b>9.2</b> TODO</a></li>
<li class="chapter" data-level="9.3" data-path="r-functions.html"><a href="r-functions.html#further-up-further-in"><i class="fa fa-check"></i><b>9.3</b> Further up, further in</a></li>
<li class="chapter" data-level="" data-path="r-functions.html"><a href="r-functions.html#funs"><i class="fa fa-check"></i>R function library</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="ggplot.html"><a href="ggplot.html"><i class="fa fa-check"></i><b>10</b> SPC Charts with <code>ggplot2</code></a></li>
<li class="chapter" data-level="11" data-path="qicharts.html"><a href="qicharts.html"><i class="fa fa-check"></i><b>11</b> Introducing qicharts2</a>
<ul>
<li class="chapter" data-level="11.1" data-path="qicharts.html"><a href="qicharts.html#a-simple-run-chart"><i class="fa fa-check"></i><b>11.1</b> A simple run chart</a></li>
<li class="chapter" data-level="11.2" data-path="qicharts.html"><a href="qicharts.html#a-simple-control-chart"><i class="fa fa-check"></i><b>11.2</b> A simple control chart</a></li>
<li class="chapter" data-level="11.3" data-path="qicharts.html"><a href="qicharts.html#excluding-data-points-from-analysis"><i class="fa fa-check"></i><b>11.3</b> Excluding data points from analysis</a></li>
<li class="chapter" data-level="11.4" data-path="qicharts.html"><a href="qicharts.html#freezing-baseline-period"><i class="fa fa-check"></i><b>11.4</b> Freezing baseline period</a></li>
<li class="chapter" data-level="11.5" data-path="qicharts.html"><a href="qicharts.html#splitting-chart-by-period"><i class="fa fa-check"></i><b>11.5</b> Splitting chart by period</a></li>
<li class="chapter" data-level="11.6" data-path="qicharts.html"><a href="qicharts.html#small-multiple-plots-for-multivariate-data"><i class="fa fa-check"></i><b>11.6</b> Small multiple plots for multivariate data</a>
<ul>
<li class="chapter" data-level="11.6.1" data-path="qicharts.html"><a href="qicharts.html#to-aggregate-or-not-to-aggregate"><i class="fa fa-check"></i><b>11.6.1</b> To aggregate or not to aggregate</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>Part 3: Case Studies and Worked Examples</b></span></li>
<li class="chapter" data-level="12" data-path="case1.html"><a href="case1.html"><i class="fa fa-check"></i><b>12</b> Case 1</a></li>
<li class="chapter" data-level="13" data-path="case2.html"><a href="case2.html"><i class="fa fa-check"></i><b>13</b> Case 2</a></li>
<li class="chapter" data-level="14" data-path="case3.html"><a href="case3.html"><i class="fa fa-check"></i><b>14</b> Case 3</a></li>
<li class="part"><span><b>Part 4: Advanced SPC Techniques</b></span></li>
<li class="part"><span><b>Part 5: Best Practices, Controversies, and Tips</b></span></li>
<li class="part"><span><b>Part 6: Conclusion and Final Thoughts</b></span></li>
<li class="part"><span><b>Part 9¾: Nerd Stuff</b></span></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="chapter" data-level="A" data-path="data-sets.html"><a href="data-sets.html"><i class="fa fa-check"></i><b>A</b> Data Sets</a>
<ul>
<li class="chapter" data-level="A.1" data-path="data-sets.html"><a href="data-sets.html#bacteremia"><i class="fa fa-check"></i><b>A.1</b> Bacteremia</a></li>
<li class="chapter" data-level="A.2" data-path="data-sets.html"><a href="data-sets.html#blood-pressure"><i class="fa fa-check"></i><b>A.2</b> Blood pressure</a></li>
<li class="chapter" data-level="A.3" data-path="data-sets.html"><a href="data-sets.html#clostridioides-difficile-infections"><i class="fa fa-check"></i><b>A.3</b> Clostridioides difficile infections</a></li>
<li class="chapter" data-level="A.4" data-path="data-sets.html"><a href="data-sets.html#ceasearian-section-delay"><i class="fa fa-check"></i><b>A.4</b> Ceasearian section delay</a></li>
<li class="chapter" data-level="A.5" data-path="data-sets.html"><a href="data-sets.html#emergency-admission-mortality"><i class="fa fa-check"></i><b>A.5</b> Emergency admission mortality</a></li>
<li class="chapter" data-level="A.6" data-path="data-sets.html"><a href="data-sets.html#on-time-ct"><i class="fa fa-check"></i><b>A.6</b> On-time CT</a></li>
<li class="chapter" data-level="A.7" data-path="data-sets.html"><a href="data-sets.html#radiation-doses"><i class="fa fa-check"></i><b>A.7</b> Radiation doses</a></li>
<li class="chapter" data-level="A.8" data-path="data-sets.html"><a href="data-sets.html#robson-group-1-births"><i class="fa fa-check"></i><b>A.8</b> Robson group 1 births</a></li>
</ul></li>
<li class="chapter" data-level="B" data-path="runs-limits.html"><a href="runs-limits.html"><i class="fa fa-check"></i><b>B</b> Critical Values for Longest Runs and Number of Crossings</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">
    Published with bookdown
  </a>
</li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Mastering Statistical Process Control Charts in Healthcare</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="limits" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">Chapter 7</span> Calculating Control Limits<a href="limits.html#limits" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In the previous chapter we established the basis for constructing SPC charts with R. In this chapter we continue with different types of control charts and how to construct their control limits.</p>
<div id="introducing-the-spc-function" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Introducing the spc() function<a href="limits.html#introducing-the-spc-function" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To avoid repeating ourselves, let’s begin by creating a function to automate the plotting for us.</p>
<p>The <code>spc()</code> function takes five arguments of which only the first, x, is mandatory. If only x is provided, a simple line chart will be drawn from the x values. If y is also provided, x values will be used for the x axis. The line arguments (cl, lcl, ucl) are used (if provided) for the centre line and control limits respectively. Line arguments may be given as either single values or vectors of the same length as x. In addition, one may provide additional arguments for the <code>plot()</code> function, e.g. main, xlab, and ylab for title and axis labels.</p>
<p>Let us test it with the blood pressure data from Chapter <a href="first-chart.html#first-chart">6</a> (Figure <a href="limits.html#fig:limits-fig1">7.1</a>).</p>
<div class="figure"><span style="display:block;" id="fig:limits-fig1"></span>
<img src="_main_files/figure-html/limits-fig1-1.svg" alt="Control chart of systolic blood pressure" width="672" />
<p class="caption">
Figure 7.1: Control chart of systolic blood pressure
</p>
</div>
<p>With this function we are now able to construct all kinds of control charts. All we need to know is how to calculate the centre line and the control limits.
## Formulas for calculation of control limits</p>
<p>The formulas for calculation control limits for the most common control charts are provided in Table <a href="limits.html#tab:limits-tab1">7.1</a>. Don’t be alarmed by the number of strange symbols, we will dissect the formulas one by one as we move along.</p>
<table>
<caption>
<span id="tab:limits-tab1">Table 7.1: </span>Formulas for calculating control limits
</caption>
<thead>
<tr>
<th style="text-align:left;">
Subgroups
</th>
<th style="text-align:left;">
Chart type
</th>
<th style="text-align:left;">
Control limits
</th>
<th style="text-align:left;">
Assumed distribution
</th>
</tr>
</thead>
<tbody>
<tr grouplength="3">
<td colspan="4" style="border-bottom: 1px solid;">
<strong>Count data</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Counts
</td>
<td style="text-align:left;">
C
</td>
<td style="text-align:left;">
<span class="math inline">\(\bar{c}\pm3\sqrt{\bar{c}}\)</span>
</td>
<td style="text-align:left;">
Poisson
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Rates
</td>
<td style="text-align:left;">
U
</td>
<td style="text-align:left;">
<span class="math inline">\(\bar{u}\pm3\sqrt{\frac{\bar{u}}{n_{i}}}\)</span>
</td>
<td style="text-align:left;">
Poisson
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Proportions
</td>
<td style="text-align:left;">
P
</td>
<td style="text-align:left;">
<span class="math inline">\(\bar{p}\pm3\sqrt{\frac{\bar{p}(1-\bar{p})}{n_{i}}}\)</span>
</td>
<td style="text-align:left;">
Binomial
</td>
</tr>
<tr grouplength="4">
<td colspan="4" style="border-bottom: 1px solid;">
<strong>Measurement data</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Individual measurements
</td>
<td style="text-align:left;">
I
</td>
<td style="text-align:left;">
<span class="math inline">\(\bar{x}\pm2.66\overline{MR}\)</span>
</td>
<td style="text-align:left;">
Normal
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Moving ranges of individual measurements
</td>
<td style="text-align:left;">
MR
</td>
<td style="text-align:left;">
<span class="math inline">\(3.267\overline{MR}\)</span>
</td>
<td style="text-align:left;">
Normal
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Averrages of 2 or more measurements
</td>
<td style="text-align:left;">
X-bar
</td>
<td style="text-align:left;">
<span class="math inline">\(\bar{\bar{x}}\pm A_{3}\bar{s}\)</span>
</td>
<td style="text-align:left;">
Normal
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Standard deviations of 2 or more measurements
</td>
<td style="text-align:left;">
S
</td>
<td style="text-align:left;">
<span class="math inline">\(B_{3}\bar{s};\ B_{4}\bar{s}\)</span>
</td>
<td style="text-align:left;">
Normal
</td>
</tr>
</tbody>
</table>
<p>Generally, data come in two flavours: count data and measurement data. <strong>Counts</strong> are positive integers that represent counts of events or cases, for example patient falls, surgical complications, or healthy babies. <strong>Measurements</strong> are data that are measured on continuous scales and may have decimals, for example blood pressure, height and weight, or waiting times.</p>
</div>
<div id="count-data" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> Count data<a href="limits.html#count-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>There are several types of count data depending on the type of counts involved. In this chapter we will limit ourselves to events and cases.</p>
<p><strong>Events</strong> are phenomena that happens from time to time and are usually rare and randomly distributed in time and space. Events can for example be the number of cancer cells found in a microscopy slide, the number of patient falls in a month, or the number of shooting stars observed in the night sky. Events often follow the poisson distribution and are presented as raw counts or rates.</p>
<p><strong>Cases</strong> represent whole units that either possess or do not posses a certain property. Cases can for example be surgical procedures that had one or more complications, patients who fell, or procedures that completed according to a standard. Cases often follow the binomial distribution and are presented as proportions or percentages.</p>
<p>For count charts in this chapter we will use the bacteremia data set:</p>
<pre><code>##        month ha_infections risk_days deaths patients
## 1 2017-01-01            24     32421     23      100
## 2 2017-02-01            29     29349     22      105
## 3 2017-03-01            26     32981     13       99
## 4 2017-04-01            16     29588     14       85
## 5 2017-05-01            28     30856     17       98
## 6 2017-06-01            16     30544     15       85</code></pre>
<p>The variables are:</p>
<ul>
<li>month (date): month of infection</li>
<li>ha_infections (numeric): number of hospital acquired infections</li>
<li>risk_days (numeric): number of patient days without infection</li>
<li>deaths (numeric): number of patients who died within 30-day after a hospital or community acquired (all-cause) infection</li>
<li>patients (numeric): number of patients with all-cause infection</li>
</ul>
<p>We use C charts for event counts and U chart for event rates. For case proportions we use the P chart.</p>
<div id="c-chart" class="section level3 hasAnchor" number="7.2.1">
<h3><span class="header-section-number">7.2.1</span> C chart<a href="limits.html#c-chart" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The C charts (C for counts) is the simplest of all control charts and the easiest to produce. The process standard deviation is simply estimated as the square root of the process mean.</p>
<p>C charts are appropriate when counting events from (nearly) equally big chunks of time or space.</p>
<p>Figure <a href="limits.html#fig:limits-c">7.2</a> shows a C chart of the monthly number of hospital acquired bacteremias.</p>
<pre><code>## UCL = 36.94952 
## CL  = 22.66667 
## LCL =  8.38381</code></pre>
<div class="figure"><span style="display:block;" id="fig:limits-c"></span>
<img src="_main_files/figure-html/limits-c-1.svg" alt="C control chart of monthly numbers of hospital acquired bacteremias" width="672" />
<p class="caption">
Figure 7.2: C control chart of monthly numbers of hospital acquired bacteremias
</p>
</div>
<p>The average monthly number of cases is 22.7, and all data points are within the control limits ranging from 8.4 to 36.9. So if nothing changes, we should expect future infection counts to be around 23, and we should not be surprised if once in a while, we observe as little as 9 or as many as 36 infections in a single month.</p>
</div>
<div id="u-chart" class="section level3 hasAnchor" number="7.2.2">
<h3><span class="header-section-number">7.2.2</span> U chart<a href="limits.html#u-chart" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>U charts are useful when events are counted over chunks of time or space that are not equally sized resulting in “unequal area of opportunity” (hence the U). In our case we might want to adjust for for the number of patient days that may vary depending on the time of year or between organisational units. The U chart adjust for this by presenting rates rather than raw counts.</p>
<p>As mentioned, events are often rare in comparison to their areas of opportunity. So to avoid very small numbers on the y-axis it may be useful to multiply the y-axis by some factor before plotting. In Figure <a href="limits.html#fig:limits-u">7.3</a> we multiply by 10,000 to display infections per 10,000 risk days rather than per day.</p>
<div class="figure"><span style="display:block;" id="fig:limits-u"></span>
<img src="_main_files/figure-html/limits-u-1.svg" alt="U chart of monthly number of infections per 10,000 risk days" width="672" />
<p class="caption">
Figure 7.3: U chart of monthly number of infections per 10,000 risk days
</p>
</div>
<p>The U chart shows that on average we have 7.5 infections per 10,000 risk days, and that all data points are between the control limits ranging from about 3.5 to 12. We see that the control limits vary depending on the denominator (risk days), for each data point. Large denominator <span class="math inline">\(\Rightarrow\)</span> narrow limits; small denominator <span class="math inline">\(\Rightarrow\)</span> wide limits.</p>
<p>In cases like this where the denominator – the area of opportunity – only varies little between subgroups, the U charts adds little compared to the C chart. For pedagogical reasons we may prefer the C chart, because it is a lot easier to relate to 23 infections per month than to 7.5 infections per 10,000 risk days.</p>
</div>
<div id="p-chart" class="section level3 hasAnchor" number="7.2.3">
<h3><span class="header-section-number">7.2.3</span> P chart<a href="limits.html#p-chart" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>P charts are for proportions (or percentages). Figure <a href="limits.html#fig:limits-p">7.4</a> shows the monthly percentage of patients with bacteremia who died within 30 days.</p>
<div class="figure"><span style="display:block;" id="fig:limits-p"></span>
<img src="_main_files/figure-html/limits-p-1.svg" alt="P chart of monthly 30-day mortality rates" width="672" />
<p class="caption">
Figure 7.4: P chart of monthly 30-day mortality rates
</p>
</div>
<p>On average the mortality is 21%, and all data points are within the control limits.</p>
</div>
</div>
<div id="measurement-data" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> Measurement data<a href="limits.html#measurement-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>For this section we will use a data set on response times for grade 2 caesarean sections, that is, the time (in minutes) it took from the decision to perform a C-section to the baby was delivered. The goal is to keep the response times below 30 minutes.</p>
<p>The csect data frame contains the date and time, the month, and the number of minutes from decision to delivery for 208 grade 2 section over a two-year period.</p>
<pre><code>##              datetime      month delay
## 1 2016-01-06 03:55:40 2016-01-01    22
## 2 2016-01-06 20:52:34 2016-01-01    22
## 3 2016-01-07 02:50:43 2016-01-01    29
## 4 2016-01-07 22:32:27 2016-01-01    28
## 5 2016-01-09 14:56:09 2016-01-01    22
## 6 2016-01-09 21:21:24 2016-01-01    20</code></pre>
<div id="i-chart-aka-x-chart" class="section level3 hasAnchor" number="7.3.1">
<h3><span class="header-section-number">7.3.1</span> I chart (aka X chart)<a href="limits.html#i-chart-aka-x-chart" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The “I” in I chart stand for “individuals” because it plots individual values from subgroups of size 1. I charts are also often referred to as X charts.</p>
<p>I charts are useful when measurements come from individual units, for example waiting times or blood pressure measurements for individual patients.</p>
<p>As we will see later, I charts are in fact useful for all kinds of data because they base their estimations on the actual variation that is present in data rather than theoretical parameters from assumed distributions. For this reason, the I chart is considered the <em>Swiss army knife</em> of SPC.</p>
<p>When subgroups consist of single values we use the pairwise absolute difference between data points, the average moving range (<span class="math inline">\(\overline{MR}\)</span>), as an estimate of the common cause variation. By dividing this value with 1.128 we get an estimate of the process standard deviation. Alternatively, we may multiply <span class="math inline">\(\overline{MR}\)</span> by 3 / 1.128 = 2.66 to get 3 <span class="math inline">\(SD\)</span>s.</p>
<p>Let’s have a look at individual delay times for the latest 60 C-sections (Figure <a href="limits.html#fig:limits-i">7.5</a>).</p>
<div class="figure"><span style="display:block;" id="fig:limits-i"></span>
<img src="_main_files/figure-html/limits-i-1.svg" alt="I-chart" width="672" />
<p class="caption">
Figure 7.5: I-chart
</p>
</div>
<p>On average, the delay time for these cases is 24 minutes. The control limits tell us that we should expect future delays to be in the range of 11 to 37 minutes. Three data points are outside the control limits (#1, #4 and #31) suggesting that these cases were special and that it might be useful to have a closer look to find out what went well with case #1 and not so well with cases #4 and #31.</p>
</div>
<div id="mr-chart" class="section level3 hasAnchor" number="7.3.2">
<h3><span class="header-section-number">7.3.2</span> MR chart<a href="limits.html#mr-chart" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The MR chart plots the moving ranges of individual values. It is a companion to the I chart. Since moving ranges can always be zero but never negative, the MR chart has no lower control limit.</p>
<div class="figure"><span style="display:block;" id="fig:limits-mr"></span>
<img src="_main_files/figure-html/limits-mr-1.svg" alt="MR-chart" width="672" />
<p class="caption">
Figure 7.6: MR-chart
</p>
</div>
<p>Note that there is one less moving range than individual values. To “synchronise” the charts, we insert an NA value at the beginning of the MR-chart.</p>
<p>We may plot the two charts together (Figure <a href="limits.html#fig:limits-imr">7.7</a>):</p>
<div class="figure"><span style="display:block;" id="fig:limits-imr"></span>
<img src="_main_files/figure-html/limits-imr-1.svg" alt="I- and MR-charts" width="672" />
<p class="caption">
Figure 7.7: I- and MR-charts
</p>
</div>
<p>The MR-chart also finds three data points outside the limits. These coincide with two of the special causes found by the I chart and supports our conclusion that these deliveries were special. Note that each data point on the I chart (except the first and last ones) produces two moving ranges on the MR chart.</p>
</div>
<div id="x-bar-chart" class="section level3 hasAnchor" number="7.3.3">
<h3><span class="header-section-number">7.3.3</span> X-bar chart<a href="limits.html#x-bar-chart" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The X-bar chart is appropriate when the subgroups consist of samples of two or more measurements.</p>
<p>To plot a control chart of the monthly average delays, we must first aggregate data to find the mean and the standard deviation of delay times and the number of sections per month.</p>
<pre><code>##        month delay.mean delay.sd delay.n
## 1 2016-01-01   23.85714 3.387653       7
## 2 2016-02-01   24.45455 6.137811      11
## 3 2016-03-01   22.45455 6.638729      11
## 4 2016-04-01   22.66667 3.041381       9
## 5 2016-05-01   22.50000 3.891382       8
## 6 2016-06-01   22.00000 6.204837       5</code></pre>
<p>Next, we calculate the centre line and the control limits using the formula in Table <a href="limits.html#tab:limits-tab1">7.1</a> where <span class="math inline">\(\bar{\bar{x}}\)</span> (pronounced x bar bar) is the weighted mean of the subgroup means, <span class="math inline">\(\bar{s}\)</span> (s bar) is the weighted mean of the subgroup standard deviations, and <span class="math inline">\(A_3\)</span> is a constant that depends on the subgroup size. See the section on <a href="limits.html#chart-constants">chart constants</a> at the end of this chapter for the R code involved in calculating <span class="math inline">\(A_3\)</span> and other constants for control chart construction.</p>
<p>With the aggregated data we are now able to construct the X-bar chart (Figure <a href="limits.html#fig:limits-xbar">7.8</a>).</p>
<div class="figure"><span style="display:block;" id="fig:limits-xbar"></span>
<img src="_main_files/figure-html/limits-xbar-1.svg" alt="X bar chart" width="672" />
<p class="caption">
Figure 7.8: X bar chart
</p>
</div>
<p>Figure <a href="limits.html#fig:limits-xbar">7.8</a> shows the <em>average</em> delay time per month. On average the delay time is 23 minutes (= centre line) and all data points fall between the control limits suggesting that the process is stable and predictable.</p>
<p>As with U and P charts the control limits vary from month to month reflecting the varying subgroup sizes – small subgroups <span class="math inline">\(\Rightarrow\)</span> wide limits; large subgroups <span class="math inline">\(\Rightarrow\)</span> narrow limits.</p>
<p>Be careful not to fall for the temptation to conclude that just because no months are above the target of 30 minutes all is well. The 30-minute target applies to the delay time of <em>individual</em> sections, not the <em>averages</em>. Even if the averages are well below the target, individuals may be above, which we already noticed from the I chart above.</p>
</div>
<div id="s-chart" class="section level3 hasAnchor" number="7.3.4">
<h3><span class="header-section-number">7.3.4</span> S chart<a href="limits.html#s-chart" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The S chart is usually plotted alongside the X-bar chart and shows the within subgroup variation. It is useful for detecting changes in the spread of data over time.</p>
<p>To calculate the centre and control limits for the S chart we need to know the process standard deviation, <span class="math inline">\(\bar{S}\)</span> (same as for the X-bar chart), and the two constants <span class="math inline">\(B_3\)</span> and <span class="math inline">\(B_4\)</span> From Table <a href="limits.html#tab:limits-tab1">7.1</a>.</p>
<div class="figure"><span style="display:block;" id="fig:limits-s"></span>
<img src="_main_files/figure-html/limits-s-1.svg" alt="S chart" width="672" />
<p class="caption">
Figure 7.9: S chart
</p>
</div>
<p>Figure <a href="limits.html#fig:limits-s">7.9</a> shows the average standard deviation of delay times per month. On average the standard deviation is 4.7 minutes and all data points fall between the control limits.</p>
<p>We may plot the X-bar and S charts together (Figure <a href="limits.html#fig:limits-xbarands">7.10</a>):</p>
<div class="figure"><span style="display:block;" id="fig:limits-xbarands"></span>
<img src="_main_files/figure-html/limits-xbarands-1.svg" alt="X-bar and S charts" width="672" />
<p class="caption">
Figure 7.10: X-bar and S charts
</p>
</div>
</div>
</div>
<div id="control-limits-in-short" class="section level2 hasAnchor" number="7.4">
<h2><span class="header-section-number">7.4</span> Control limits in short<a href="limits.html#control-limits-in-short" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Control limits attempt to estimate the boundaries of the natural common cause process variation. They are placed 3 standard deviations above and below the centre line, which is the (weighted) mean of the subgroup means.</p>
<p>The procedure for calculating control limits depends on the type of data involved, but the interpretation of charts are the same regardless of data type.</p>
<p>In the next chapter we will improve our plots by adding visual clues to highlight signs of non-random variation.</p>
<hr />
</div>
<div id="chart-constants" class="section level2 unnumbered hasAnchor">
<h2>Control chart constants<a href="limits.html#chart-constants" class="anchor-section" aria-label="Anchor link to header"></a></h2>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="first-chart.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="highlighting.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
