<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>B Basic Statistical Concepts | Mastering Statistical Process Control Charts in Healthcare</title>
  <meta name="description" content="This is a book (currently under early development) for data scientists about the practical application of statistical process control methodology in healthcare." />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="B Basic Statistical Concepts | Mastering Statistical Process Control Charts in Healthcare" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a book (currently under early development) for data scientists about the practical application of statistical process control methodology in healthcare." />
  <meta name="github-repo" content="anhoej/spc4hc" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="B Basic Statistical Concepts | Mastering Statistical Process Control Charts in Healthcare" />
  
  <meta name="twitter:description" content="This is a book (currently under early development) for data scientists about the practical application of statistical process control methodology in healthcare." />
  

<meta name="author" content="Jacob Anhøj &amp; Mohammed Amin Mohammed" />


<meta name="date" content="2025-06-08" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="data-sets.html"/>
<link rel="next" href="diagnostics.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">
    Mastering SPC charts
  </a>
</li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> cover-image: path to the social sharing image like images/cover.jpg</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html#what-sets-this-book-apart"><i class="fa fa-check"></i>What Sets This Book Apart?</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html#prerequisites"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html#how-to-use-this-book"><i class="fa fa-check"></i>How to Use This Book</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html#about-the-authors"><i class="fa fa-check"></i>About the Authors</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="synopsis.html"><a href="synopsis.html"><i class="fa fa-check"></i>Synopsis</a>
<ul>
<li class="chapter" data-level="" data-path="synopsis.html"><a href="synopsis.html#introduction"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="" data-path="synopsis.html"><a href="synopsis.html#part-1-understanding-variation"><i class="fa fa-check"></i>Part 1: Understanding Variation</a></li>
<li class="chapter" data-level="" data-path="synopsis.html"><a href="synopsis.html#part-2-constructing-spc-charts-with-r"><i class="fa fa-check"></i>Part 2: Constructing SPC Charts with R</a></li>
<li class="chapter" data-level="" data-path="synopsis.html"><a href="synopsis.html#part-3-case-studies-and-worked-examples"><i class="fa fa-check"></i>Part 3: Case Studies and Worked Examples</a></li>
<li class="chapter" data-level="" data-path="synopsis.html"><a href="synopsis.html#part-4-advanced-spc-techniques"><i class="fa fa-check"></i>Part 4: Advanced SPC Techniques</a></li>
<li class="chapter" data-level="" data-path="synopsis.html"><a href="synopsis.html#part-5-best-practices-controversies-and-tips"><i class="fa fa-check"></i>Part 5: Best Practices, Controversies, and Tips</a></li>
<li class="chapter" data-level="" data-path="synopsis.html"><a href="synopsis.html#part-6-conclusion-and-final-thoughts"><i class="fa fa-check"></i>Part 6: Conclusion and Final Thoughts</a></li>
<li class="chapter" data-level="" data-path="synopsis.html"><a href="synopsis.html#appendices"><i class="fa fa-check"></i>Appendices</a></li>
</ul></li>
<li class="part"><span><b>Part 1: Understanding Variation</b></span></li>
<li class="chapter" data-level="2" data-path="variation.html"><a href="variation.html"><i class="fa fa-check"></i><b>2</b> Understanding Variation</a>
<ul>
<li class="chapter" data-level="2.1" data-path="variation.html"><a href="variation.html#spc-and-the-nature-of-variation"><i class="fa fa-check"></i><b>2.1</b> SPC and the nature of variation</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="charts-intro.html"><a href="charts-intro.html"><i class="fa fa-check"></i><b>3</b> Understanding SPC Charts</a>
<ul>
<li class="chapter" data-level="3.1" data-path="charts-intro.html"><a href="charts-intro.html#anatomy-and-physiology-of-spc-charts"><i class="fa fa-check"></i><b>3.1</b> Anatomy and physiology of SPC charts</a></li>
<li class="chapter" data-level="3.2" data-path="charts-intro.html"><a href="charts-intro.html#why-3-sigma-limits"><i class="fa fa-check"></i><b>3.2</b> Why 3-sigma limits?</a></li>
<li class="chapter" data-level="3.3" data-path="charts-intro.html"><a href="charts-intro.html#some-common-types-of-control-charts-the-magnificent-seven"><i class="fa fa-check"></i><b>3.3</b> Some common types of control charts: The Magnificent Seven</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="charts-intro.html"><a href="charts-intro.html#counts"><i class="fa fa-check"></i><b>3.3.1</b> Counts</a></li>
<li class="chapter" data-level="3.3.2" data-path="charts-intro.html"><a href="charts-intro.html#measurements"><i class="fa fa-check"></i><b>3.3.2</b> Measurements</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="charts-intro.html"><a href="charts-intro.html#summary-of-common-spc-charts"><i class="fa fa-check"></i><b>3.4</b> Summary of common SPC charts</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="testing.html"><a href="testing.html"><i class="fa fa-check"></i><b>4</b> Looking for Signals on SPC charts – Beyond the 3-Sigma Rule</a>
<ul>
<li class="chapter" data-level="4.1" data-path="testing.html"><a href="testing.html#patterns-of-non-random-variation-in-time-series-data"><i class="fa fa-check"></i><b>4.1</b> Patterns of non-random variation in time series data</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="testing.html"><a href="testing.html#freaks"><i class="fa fa-check"></i><b>4.1.1</b> Freaks</a></li>
<li class="chapter" data-level="4.1.2" data-path="testing.html"><a href="testing.html#shifts"><i class="fa fa-check"></i><b>4.1.2</b> Shifts</a></li>
<li class="chapter" data-level="4.1.3" data-path="testing.html"><a href="testing.html#trends"><i class="fa fa-check"></i><b>4.1.3</b> Trends</a></li>
<li class="chapter" data-level="4.1.4" data-path="testing.html"><a href="testing.html#other-unusual-patterns"><i class="fa fa-check"></i><b>4.1.4</b> Other unusual patterns</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="testing.html"><a href="testing.html#spc-rules"><i class="fa fa-check"></i><b>4.2</b> SPC rules</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="testing.html"><a href="testing.html#tests-based-on-sigma-limits"><i class="fa fa-check"></i><b>4.2.1</b> Tests based on sigma limits</a></li>
<li class="chapter" data-level="4.2.2" data-path="testing.html"><a href="testing.html#runs-analysis-tests-based-on-the-distribution-of-data-points-around-the-centre-line"><i class="fa fa-check"></i><b>4.2.2</b> Runs analysis – tests based on the distribution of data points around the centre line</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="testing.html"><a href="testing.html#spc-charts-without-borders-using-run-charts"><i class="fa fa-check"></i><b>4.3</b> SPC charts without borders – using run charts</a></li>
<li class="chapter" data-level="4.4" data-path="testing.html"><a href="testing.html#a-practical-approach-to-spc-analysis"><i class="fa fa-check"></i><b>4.4</b> A practical approach to SPC analysis</a></li>
<li class="chapter" data-level="4.5" data-path="testing.html"><a href="testing.html#spc-rules-in-summary"><i class="fa fa-check"></i><b>4.5</b> SPC rules in summary</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="using.html"><a href="using.html"><i class="fa fa-check"></i><b>5</b> Using SPC in healthcare</a>
<ul>
<li class="chapter" data-level="5.1" data-path="using.html"><a href="using.html#using-spc-to-monitor-a-process"><i class="fa fa-check"></i><b>5.1</b> Using SPC to monitor a process</a></li>
<li class="chapter" data-level="5.2" data-path="using.html"><a href="using.html#using-spc-to-improve-a-process"><i class="fa fa-check"></i><b>5.2</b> Using SPC to improve a process</a></li>
<li class="chapter" data-level="5.3" data-path="using.html"><a href="using.html#successful-use-of-spc-in-healthcare"><i class="fa fa-check"></i><b>5.3</b> Successful use of SPC in healthcare</a></li>
</ul></li>
<li class="part"><span><b>Part 2: Constructing SPC Charts</b></span></li>
<li class="chapter" data-level="6" data-path="first-chart.html"><a href="first-chart.html"><i class="fa fa-check"></i><b>6</b> Your First SPC Charts With Base R</a>
<ul>
<li class="chapter" data-level="6.1" data-path="first-chart.html"><a href="first-chart.html#a-run-chart-of-blood-pressure-data"><i class="fa fa-check"></i><b>6.1</b> A run chart of blood pressure data</a></li>
<li class="chapter" data-level="6.2" data-path="first-chart.html"><a href="first-chart.html#adding-control-limits-to-produce-a-control-chart"><i class="fa fa-check"></i><b>6.2</b> Adding control limits to produce a control chart</a></li>
<li class="chapter" data-level="6.3" data-path="first-chart.html"><a href="first-chart.html#thats-all-folks"><i class="fa fa-check"></i><b>6.3</b> That’s all, Folks!</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="limits.html"><a href="limits.html"><i class="fa fa-check"></i><b>7</b> Calculating Control Limits</a>
<ul>
<li class="chapter" data-level="7.1" data-path="limits.html"><a href="limits.html#introducing-the-spc-function"><i class="fa fa-check"></i><b>7.1</b> Introducing the spc() function</a></li>
<li class="chapter" data-level="7.2" data-path="limits.html"><a href="limits.html#formulas-for-calculation-of-control-limits"><i class="fa fa-check"></i><b>7.2</b> Formulas for calculation of control limits</a></li>
<li class="chapter" data-level="7.3" data-path="limits.html"><a href="limits.html#count-data"><i class="fa fa-check"></i><b>7.3</b> Count data</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="limits.html"><a href="limits.html#c-chart"><i class="fa fa-check"></i><b>7.3.1</b> C chart</a></li>
<li class="chapter" data-level="7.3.2" data-path="limits.html"><a href="limits.html#u-chart"><i class="fa fa-check"></i><b>7.3.2</b> U chart</a></li>
<li class="chapter" data-level="7.3.3" data-path="limits.html"><a href="limits.html#p-chart"><i class="fa fa-check"></i><b>7.3.3</b> P chart</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="limits.html"><a href="limits.html#measurement-data"><i class="fa fa-check"></i><b>7.4</b> Measurement data</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="limits.html"><a href="limits.html#i-chart-aka-x-chart"><i class="fa fa-check"></i><b>7.4.1</b> I chart (aka X chart)</a></li>
<li class="chapter" data-level="7.4.2" data-path="limits.html"><a href="limits.html#mr-chart"><i class="fa fa-check"></i><b>7.4.2</b> MR chart</a></li>
<li class="chapter" data-level="7.4.3" data-path="limits.html"><a href="limits.html#x-bar-chart"><i class="fa fa-check"></i><b>7.4.3</b> X-bar chart</a></li>
<li class="chapter" data-level="7.4.4" data-path="limits.html"><a href="limits.html#s-chart"><i class="fa fa-check"></i><b>7.4.4</b> S chart</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="limits.html"><a href="limits.html#control-limits-in-short"><i class="fa fa-check"></i><b>7.5</b> Control limits in short</a></li>
<li class="chapter" data-level="" data-path="limits.html"><a href="limits.html#chart-constants"><i class="fa fa-check"></i>Control chart constants</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="highlighting.html"><a href="highlighting.html"><i class="fa fa-check"></i><b>8</b> Highlighting Freaks, Shifts, and Trends</a>
<ul>
<li class="chapter" data-level="8.1" data-path="highlighting.html"><a href="highlighting.html#introducing-the-cdiff-data-set"><i class="fa fa-check"></i><b>8.1</b> Introducing the cdiff data set</a></li>
<li class="chapter" data-level="8.2" data-path="highlighting.html"><a href="highlighting.html#improved-spc-function"><i class="fa fa-check"></i><b>8.2</b> Improved <code>spc()</code> function</a></li>
<li class="chapter" data-level="8.3" data-path="highlighting.html"><a href="highlighting.html#highlighting-special-cause-variation-in-short"><i class="fa fa-check"></i><b>8.3</b> Highlighting special cause variation in short</a></li>
<li class="chapter" data-level="" data-path="highlighting.html"><a href="highlighting.html#r-function-for-runs-analysis"><i class="fa fa-check"></i>R function for runs analysis</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="r-functions.html"><a href="r-functions.html"><i class="fa fa-check"></i><b>9</b> Core R Functions to Construct SPC Charts</a>
<ul>
<li class="chapter" data-level="9.1" data-path="r-functions.html"><a href="r-functions.html#examples"><i class="fa fa-check"></i><b>9.1</b> Examples</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="r-functions.html"><a href="r-functions.html#run-chart"><i class="fa fa-check"></i><b>9.1.1</b> Run chart</a></li>
<li class="chapter" data-level="9.1.2" data-path="r-functions.html"><a href="r-functions.html#i-and-mr-charts-for-individual-measurements"><i class="fa fa-check"></i><b>9.1.2</b> I and MR charts for individual measurements</a></li>
<li class="chapter" data-level="9.1.3" data-path="r-functions.html"><a href="r-functions.html#x-bar-and-s-charts-for-averages-and-standard-deviations-of-measurements"><i class="fa fa-check"></i><b>9.1.3</b> X-bar and S charts for averages and standard deviations of measurements</a></li>
<li class="chapter" data-level="9.1.4" data-path="r-functions.html"><a href="r-functions.html#c-and-u-charts-for-counts-and-rates"><i class="fa fa-check"></i><b>9.1.4</b> C and U charts for counts and rates</a></li>
<li class="chapter" data-level="9.1.5" data-path="r-functions.html"><a href="r-functions.html#p-chart-for-percentages"><i class="fa fa-check"></i><b>9.1.5</b> P chart for percentages</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="r-functions.html"><a href="r-functions.html#todo"><i class="fa fa-check"></i><b>9.2</b> TODO</a></li>
<li class="chapter" data-level="9.3" data-path="r-functions.html"><a href="r-functions.html#further-up-further-in"><i class="fa fa-check"></i><b>9.3</b> Further up, further in</a></li>
<li class="chapter" data-level="" data-path="r-functions.html"><a href="r-functions.html#funs"><i class="fa fa-check"></i>R function library</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="ggplot.html"><a href="ggplot.html"><i class="fa fa-check"></i><b>10</b> SPC Charts with ggplot2</a>
<ul>
<li class="chapter" data-level="10.1" data-path="ggplot.html"><a href="ggplot.html#creating-an-spc-object-for-later-plotting"><i class="fa fa-check"></i><b>10.1</b> Creating an SPC object for later plotting</a></li>
<li class="chapter" data-level="10.2" data-path="ggplot.html"><a href="ggplot.html#making-a-new-plot-function-based-on-ggplot2"><i class="fa fa-check"></i><b>10.2</b> Making a new plot function based on ggplot2</a></li>
<li class="chapter" data-level="10.3" data-path="ggplot.html"><a href="ggplot.html#customising-the-plotting-theme"><i class="fa fa-check"></i><b>10.3</b> Customising the plotting theme</a></li>
<li class="chapter" data-level="10.4" data-path="ggplot.html"><a href="ggplot.html#preparing-for-qicharts2"><i class="fa fa-check"></i><b>10.4</b> Preparing for qicharts2</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="qicharts.html"><a href="qicharts.html"><i class="fa fa-check"></i><b>11</b> Introducing qicharts2</a>
<ul>
<li class="chapter" data-level="11.1" data-path="qicharts.html"><a href="qicharts.html#a-simple-run-chart"><i class="fa fa-check"></i><b>11.1</b> A simple run chart</a></li>
<li class="chapter" data-level="11.2" data-path="qicharts.html"><a href="qicharts.html#a-simple-control-chart"><i class="fa fa-check"></i><b>11.2</b> A simple control chart</a></li>
<li class="chapter" data-level="11.3" data-path="qicharts.html"><a href="qicharts.html#excluding-data-points-from-analysis"><i class="fa fa-check"></i><b>11.3</b> Excluding data points from analysis</a></li>
<li class="chapter" data-level="11.4" data-path="qicharts.html"><a href="qicharts.html#freezing-baseline-period"><i class="fa fa-check"></i><b>11.4</b> Freezing baseline period</a></li>
<li class="chapter" data-level="11.5" data-path="qicharts.html"><a href="qicharts.html#splitting-chart-by-period"><i class="fa fa-check"></i><b>11.5</b> Splitting chart by period</a></li>
<li class="chapter" data-level="11.6" data-path="qicharts.html"><a href="qicharts.html#small-multiple-plots-for-multivariate-data"><i class="fa fa-check"></i><b>11.6</b> Small multiple plots for multivariate data</a>
<ul>
<li class="chapter" data-level="11.6.1" data-path="qicharts.html"><a href="qicharts.html#to-aggregate-or-not-to-aggregate"><i class="fa fa-check"></i><b>11.6.1</b> To aggregate or not to aggregate</a></li>
</ul></li>
<li class="chapter" data-level="11.7" data-path="qicharts.html"><a href="qicharts.html#qicharts2-in-short"><i class="fa fa-check"></i><b>11.7</b> qicharts2 in short</a></li>
</ul></li>
<li class="part"><span><b>Part 3: Case Studies and Worked Examples</b></span></li>
<li class="chapter" data-level="12" data-path="case-1.html"><a href="case-1.html"><i class="fa fa-check"></i><b>12</b> Case 1:</a></li>
<li class="part"><span><b>Part 4: Advanced SPC Techniques</b></span></li>
<li class="chapter" data-level="13" data-path="screenedmr.html"><a href="screenedmr.html"><i class="fa fa-check"></i><b>13</b> Screened I Chart – eliminating freak moving ranges before calculating limits</a></li>
<li class="chapter" data-level="14" data-path="spc-charts-for-rare-events.html"><a href="spc-charts-for-rare-events.html"><i class="fa fa-check"></i><b>14</b> SPC Charts for Rare Events</a>
<ul>
<li class="chapter" data-level="14.1" data-path="spc-charts-for-rare-events.html"><a href="spc-charts-for-rare-events.html#introducing-the-birth-dataset"><i class="fa fa-check"></i><b>14.1</b> Introducing the birth dataset</a></li>
<li class="chapter" data-level="14.2" data-path="spc-charts-for-rare-events.html"><a href="spc-charts-for-rare-events.html#g-charts-for-opportunities-between-cases"><i class="fa fa-check"></i><b>14.2</b> G charts for opportunities between cases</a></li>
<li class="chapter" data-level="14.3" data-path="spc-charts-for-rare-events.html"><a href="spc-charts-for-rare-events.html#t-charts-for-time-between-events"><i class="fa fa-check"></i><b>14.3</b> T charts for time between events</a></li>
<li class="chapter" data-level="14.4" data-path="spc-charts-for-rare-events.html"><a href="spc-charts-for-rare-events.html#the-bernoulli-cusum-chart-for-binary-data"><i class="fa fa-check"></i><b>14.4</b> The Bernoulli CUSUM chart for binary data</a></li>
<li class="chapter" data-level="14.5" data-path="spc-charts-for-rare-events.html"><a href="spc-charts-for-rare-events.html#selecting-the-rigth-chart-for-rare-events"><i class="fa fa-check"></i><b>14.5</b> Selecting the rigth chart for rare events</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="prime-charts-for-count-data-with-very-large-subgroups.html"><a href="prime-charts-for-count-data-with-very-large-subgroups.html"><i class="fa fa-check"></i><b>15</b> Prime Charts for Count Data with Very Large Subgroups</a>
<ul>
<li class="chapter" data-level="15.1" data-path="prime-charts-for-count-data-with-very-large-subgroups.html"><a href="prime-charts-for-count-data-with-very-large-subgroups.html#laneys-prime-chart"><i class="fa fa-check"></i><b>15.1</b> Laney’s prime chart</a></li>
<li class="chapter" data-level="15.2" data-path="prime-charts-for-count-data-with-very-large-subgroups.html"><a href="prime-charts-for-count-data-with-very-large-subgroups.html#when-to-use-prime-charts"><i class="fa fa-check"></i><b>15.2</b> When to use prime charts</a></li>
<li class="chapter" data-level="" data-path="prime-charts-for-count-data-with-very-large-subgroups.html"><a href="prime-charts-for-count-data-with-very-large-subgroups.html#pp-data"><i class="fa fa-check"></i>Example data for P prime charts</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="i-prime-chart-for-measurement-data-with-variable-subgroup-sizes-and-more.html"><a href="i-prime-chart-for-measurement-data-with-variable-subgroup-sizes-and-more.html"><i class="fa fa-check"></i><b>16</b> I Prime Chart for Measurement Data With Variable Subgroup Sizes (and more)</a>
<ul>
<li class="chapter" data-level="16.0.1" data-path="i-prime-chart-for-measurement-data-with-variable-subgroup-sizes-and-more.html"><a href="i-prime-chart-for-measurement-data-with-variable-subgroup-sizes-and-more.html#procedure-for-calculating-centre-line-and-control-limits"><i class="fa fa-check"></i><b>16.0.1</b> Procedure for calculating centre line and control limits</a></li>
<li class="chapter" data-level="16.1" data-path="i-prime-chart-for-measurement-data-with-variable-subgroup-sizes-and-more.html"><a href="i-prime-chart-for-measurement-data-with-variable-subgroup-sizes-and-more.html#i-charts-for-measument-data-with-variable-subgroup-sizes"><i class="fa fa-check"></i><b>16.1</b> I’ charts for measument data with variable subgroup sizes</a></li>
<li class="chapter" data-level="16.2" data-path="i-prime-chart-for-measurement-data-with-variable-subgroup-sizes-and-more.html"><a href="i-prime-chart-for-measurement-data-with-variable-subgroup-sizes-and-more.html#one-chart-to-rule-them-all"><i class="fa fa-check"></i><b>16.2</b> One chart to rule them all?</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="funnel-plots-for-categorical-subgroups.html"><a href="funnel-plots-for-categorical-subgroups.html"><i class="fa fa-check"></i><b>17</b> Funnel Plots for Categorical Subgroups</a></li>
<li class="chapter" data-level="18" data-path="pareto-charts-for-ranking-problems.html"><a href="pareto-charts-for-ranking-problems.html"><i class="fa fa-check"></i><b>18</b> Pareto Charts for Ranking Problems</a></li>
<li class="part"><span><b>Part 5: Best Practices, Controversies, and Tips</b></span></li>
<li class="chapter" data-level="19" data-path="tips-for-effective-spc-implementation.html"><a href="tips-for-effective-spc-implementation.html"><i class="fa fa-check"></i><b>19</b> Tips for Effective SPC Implementation</a></li>
<li class="chapter" data-level="20" data-path="common-pitfalls-to-avoid.html"><a href="common-pitfalls-to-avoid.html"><i class="fa fa-check"></i><b>20</b> Common Pitfalls to Avoid</a></li>
<li class="chapter" data-level="21" data-path="a-note-on-rational-subgrouping-and-sampling.html"><a href="a-note-on-rational-subgrouping-and-sampling.html"><i class="fa fa-check"></i><b>21</b> A Note on Rational Subgrouping and Sampling</a></li>
<li class="chapter" data-level="22" data-path="do-data-have-to-be-normally-distributed-and-why-not.html"><a href="do-data-have-to-be-normally-distributed-and-why-not.html"><i class="fa fa-check"></i><b>22</b> Do Data Have to Be Normally Distributed? – and why not</a></li>
<li class="chapter" data-level="23" data-path="high-volume-data.html"><a href="high-volume-data.html"><i class="fa fa-check"></i><b>23</b> High Volume Data</a></li>
<li class="chapter" data-level="24" data-path="scaling-up-charts.html"><a href="scaling-up-charts.html"><i class="fa fa-check"></i><b>24</b> Scaling Up Charts</a></li>
<li class="part"><span><b>Part 6: Conclusion and Final Thoughts</b></span></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="chapter" data-level="A" data-path="data-sets.html"><a href="data-sets.html"><i class="fa fa-check"></i><b>A</b> Data Sets</a></li>
<li class="chapter" data-level="B" data-path="stat-concepts.html"><a href="stat-concepts.html"><i class="fa fa-check"></i><b>B</b> Basic Statistical Concepts</a>
<ul>
<li class="chapter" data-level="B.1" data-path="stat-concepts.html"><a href="stat-concepts.html#data-types"><i class="fa fa-check"></i><b>B.1</b> Data types</a>
<ul>
<li class="chapter" data-level="B.1.1" data-path="stat-concepts.html"><a href="stat-concepts.html#categorical-data"><i class="fa fa-check"></i><b>B.1.1</b> Categorical data</a></li>
<li class="chapter" data-level="B.1.2" data-path="stat-concepts.html"><a href="stat-concepts.html#numerical-data"><i class="fa fa-check"></i><b>B.1.2</b> Numerical data</a></li>
</ul></li>
<li class="chapter" data-level="B.2" data-path="stat-concepts.html"><a href="stat-concepts.html#summarising-categorical-data"><i class="fa fa-check"></i><b>B.2</b> Summarising categorical data</a></li>
<li class="chapter" data-level="B.3" data-path="stat-concepts.html"><a href="stat-concepts.html#summarising-numerical-data"><i class="fa fa-check"></i><b>B.3</b> Summarising numerical data</a>
<ul>
<li class="chapter" data-level="B.3.1" data-path="stat-concepts.html"><a href="stat-concepts.html#centre"><i class="fa fa-check"></i><b>B.3.1</b> Centre</a></li>
<li class="chapter" data-level="B.3.2" data-path="stat-concepts.html"><a href="stat-concepts.html#shape"><i class="fa fa-check"></i><b>B.3.2</b> Shape</a></li>
<li class="chapter" data-level="B.3.3" data-path="stat-concepts.html"><a href="stat-concepts.html#spread"><i class="fa fa-check"></i><b>B.3.3</b> Spread</a></li>
</ul></li>
<li class="chapter" data-level="B.4" data-path="stat-concepts.html"><a href="stat-concepts.html#theoretical-distributions"><i class="fa fa-check"></i><b>B.4</b> Theoretical distributions</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="diagnostics.html"><a href="diagnostics.html"><i class="fa fa-check"></i><b>C</b> Two types of errors when using SPC</a>
<ul>
<li class="chapter" data-level="C.1" data-path="diagnostics.html"><a href="diagnostics.html#quantifying-the-diagnostic-error-of-spc-charts"><i class="fa fa-check"></i><b>C.1</b> Quantifying the diagnostic error of SPC charts</a>
<ul>
<li class="chapter" data-level="C.1.1" data-path="diagnostics.html"><a href="diagnostics.html#average-run-length"><i class="fa fa-check"></i><b>C.1.1</b> Average run length</a></li>
<li class="chapter" data-level="C.1.2" data-path="diagnostics.html"><a href="diagnostics.html#likelihood-ratios"><i class="fa fa-check"></i><b>C.1.2</b> Likelihood ratios</a></li>
</ul></li>
<li class="chapter" data-level="C.2" data-path="diagnostics.html"><a href="diagnostics.html#conclusion-keeping-the-balance"><i class="fa fa-check"></i><b>C.2</b> Conclusion: Keeping the balance</a></li>
</ul></li>
<li class="chapter" data-level="D" data-path="r-notes.html"><a href="r-notes.html"><i class="fa fa-check"></i><b>D</b> r Notes</a>
<ul>
<li class="chapter" data-level="D.1" data-path="r-notes.html"><a href="r-notes.html#data-structures-and-classes"><i class="fa fa-check"></i><b>D.1</b> Data structures and classes</a></li>
<li class="chapter" data-level="D.2" data-path="r-notes.html"><a href="r-notes.html#plot-ready-data-frames"><i class="fa fa-check"></i><b>D.2</b> Plot-ready data frames</a></li>
<li class="chapter" data-level="D.3" data-path="r-notes.html"><a href="r-notes.html#importing-data-from-text-files"><i class="fa fa-check"></i><b>D.3</b> Importing data from text files</a></li>
<li class="chapter" data-level="D.4" data-path="r-notes.html"><a href="r-notes.html#manipulating-data-frames"><i class="fa fa-check"></i><b>D.4</b> Manipulating data frames</a>
<ul>
<li class="chapter" data-level="D.4.1" data-path="r-notes.html"><a href="r-notes.html#adding-variables-to-data-frames"><i class="fa fa-check"></i><b>D.4.1</b> Adding variables to data frames</a></li>
<li class="chapter" data-level="D.4.2" data-path="r-notes.html"><a href="r-notes.html#aggregating-data-frames"><i class="fa fa-check"></i><b>D.4.2</b> Aggregating data frames</a></li>
</ul></li>
<li class="chapter" data-level="D.5" data-path="r-notes.html"><a href="r-notes.html#tips-and-tricks"><i class="fa fa-check"></i><b>D.5</b> Tips and tricks</a>
<ul>
<li class="chapter" data-level="D.5.1" data-path="r-notes.html"><a href="r-notes.html#cutting-dates-and-datetimes"><i class="fa fa-check"></i><b>D.5.1</b> Cutting dates and datetimes</a></li>
<li class="chapter" data-level="D.5.2" data-path="r-notes.html"><a href="r-notes.html#getting-age-from-date-of-birth"><i class="fa fa-check"></i><b>D.5.2</b> Getting age from date of birth</a></li>
<li class="chapter" data-level="D.5.3" data-path="r-notes.html"><a href="r-notes.html#naming-files-and-variables"><i class="fa fa-check"></i><b>D.5.3</b> Naming files and variables</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="E" data-path="runs-limits.html"><a href="runs-limits.html"><i class="fa fa-check"></i><b>E</b> Critical Values for Longest Runs and Number of Crossings</a></li>
<li class="chapter" data-level="F" data-path="resources.html"><a href="resources.html"><i class="fa fa-check"></i><b>F</b> Resources and Further Readings</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">
    Published with bookdown
  </a>
</li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Mastering Statistical Process Control Charts in Healthcare</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="stat-concepts" class="section level1 hasAnchor" number="26">
<h1><span class="header-section-number">B</span> Basic Statistical Concepts<a href="stat-concepts.html#stat-concepts" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="data-types" class="section level2 hasAnchor" number="26.1">
<h2><span class="header-section-number">B.1</span> Data types<a href="stat-concepts.html#data-types" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Data can be classified into several types, with the most common being categorical and numerical data.</p>
<div id="categorical-data" class="section level3 hasAnchor" number="26.1.1">
<h3><span class="header-section-number">B.1.1</span> Categorical data<a href="stat-concepts.html#categorical-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Categorical data, also known as qualitative data, represent characteristics that cannot be meaningfully measured on a numerical scale, for example [red, green, blue], [medicine, surgery, psychiatry] or [low, medium, high]. Categorical data cannot be directly analysed using arithmetic operations – what is the sum of red, green and blue, for example?</p>
<p>Categorical data can be divided into:</p>
<ul>
<li><p>Nominal data: Categories without a natural order, e.g. [red, green, blue] or [medicine, surgery, psychiatry].</p></li>
<li><p>Ordinal data: Categories with a meaningful order, but without consistent intervals between them, e.g. [low &lt; medium &lt; high].</p></li>
</ul>
<p>If categorical data consist of only two possible values – such as yes/no, true/false or dead/alive – they are referred to as binary or binomial data.</p>
<p>Categorical data can be transformed into numerical form by counting the number of observations in each category. In some (rare) cases, it may be appropriate to assign numerical values to ordinal data, such as school grades, thereby enabling the use of arithmetic operations. However, we should be careful not to impose numerical values on any ordinal data unless the intervals are consistent and well-defined. It may be tempting to converts, for instance, cancer stages [I, II, III] into numbers [1, 2, 3]. But this will only make sense, if cancer stage II is exactly twice as severe as stage I, and stage III three times as severe.</p>
<p>Note that some categorical data – such as postal codes, insurance numbers and phone numbers – may appear numerical but are actually categorical. To identify such cases, ask whether it makes sense to calculate a sum or an average. If not, the values should be treated as categories rather than numbers.</p>
</div>
<div id="numerical-data" class="section level3 hasAnchor" number="26.1.2">
<h3><span class="header-section-number">B.1.2</span> Numerical data<a href="stat-concepts.html#numerical-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Numerical data, also known as quantitative data, consist of values that represent measurable quantities. These data can be meaningfully analysed using arithmetic operations such as addition or subtraction.</p>
<p>Numerical data fall in two main subtypes:</p>
<ul>
<li><p>Discrete data: Distinct, separate values that result from counting and are always expressed as whole numbers (including zero). Examples include number of pregnancies, pressure ulcers and hospital admissions.</p></li>
<li><p>Continuous data: Values obtained through measurement that can take on any value within a given range, including decimals, fractions and negative numbers. Examples include height, weight, waiting time and blood pressure.</p></li>
</ul>
<p>Just as categorical data can be converted into numbers through counting, numerical data can be transformed into categories by grouping values into defined ranges — for example, converting exact blood pressure readings into hypertension categories such as normal, elevated, stage 1 hypertension, and stage 2 hypertension.</p>
</div>
</div>
<div id="summarising-categorical-data" class="section level2 hasAnchor" number="26.2">
<h2><span class="header-section-number">B.2</span> Summarising categorical data<a href="stat-concepts.html#summarising-categorical-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this section we use the <a href="#adverse-events">Adverse events</a> dataset assigned to the variable ae.</p>
<p>As mentioned, categorical data are most commonly summarised by counting the number of observations in each category, typically presented as frequencies or proportions (or percentages). In R, this can be easily done using the table() function.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="stat-concepts.html#cb1-1" tabindex="-1"></a><span class="co"># count number of adverse events in each category</span></span>
<span id="cb1-2"><a href="stat-concepts.html#cb1-2" tabindex="-1"></a>(ae.tbl <span class="ot">&lt;-</span> <span class="fu">table</span>(ae<span class="sc">$</span>category))</span></code></pre></div>
<pre><code>## 
##             Fall Gastrointestinal        Infection       Medication 
##                1               40               34               18 
##            Other   Pressure ulcer        Procedure 
##                4                5               29</code></pre>
<p>A useful visualisation of categorical data is the bar chart displaying either the frequencies or proportions in each category:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="stat-concepts.html#cb3-1" tabindex="-1"></a><span class="co"># plot frequencies</span></span>
<span id="cb3-2"><a href="stat-concepts.html#cb3-2" tabindex="-1"></a><span class="fu">barplot</span>(ae.tbl)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:stat-bar1"></span>
<img src="_main_files/figure-html/stat-bar1-1.svg" alt="Bar chart of adverse event frequencies" width="960" />
<p class="caption">
Figure B.1: Bar chart of adverse event frequencies
</p>
</div>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="stat-concepts.html#cb4-1" tabindex="-1"></a><span class="co"># plot proportions</span></span>
<span id="cb4-2"><a href="stat-concepts.html#cb4-2" tabindex="-1"></a><span class="fu">barplot</span>(<span class="fu">prop.table</span>(ae.tbl))</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:stat-bar2"></span>
<img src="_main_files/figure-html/stat-bar2-1.svg" alt="Bar chart of adverse event proportions." width="960" />
<p class="caption">
Figure B.2: Bar chart of adverse event proportions.
</p>
</div>
<p>The only difference between figures <a href="stat-concepts.html#fig:stat-bar1">B.1</a> and <a href="stat-concepts.html#fig:stat-bar2">B.2</a> is the y-axis scale.</p>
<p>For binary data, a summary may simply involve calculating the proportion or percentage of one category relative to the total, for example the proportion of adverse events with fatal outcome:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="stat-concepts.html#cb5-1" tabindex="-1"></a><span class="co"># proportion of fatal adverse events (severity = &#39;I&#39;).</span></span>
<span id="cb5-2"><a href="stat-concepts.html#cb5-2" tabindex="-1"></a><span class="fu">mean</span>(ae<span class="sc">$</span>severity <span class="sc">==</span> <span class="st">&#39;I&#39;</span>)</span></code></pre></div>
<pre><code>## [1] 0.007633588</code></pre>
</div>
<div id="summarising-numerical-data" class="section level2 hasAnchor" number="26.3">
<h2><span class="header-section-number">B.3</span> Summarising numerical data<a href="stat-concepts.html#summarising-numerical-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>For this section we use the <a href="#robson-group-1-births">Robson group 1 births</a> and the <a href="#renography-doses">Renography doses</a> datasets assigned to the births and reno variables respectively.</p>
<p>Numerical data are commonly summarised using three key characteristics: central tendency, distribution shape and spread (variation). In R, the summary() function provides a quick overview of all three:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="stat-concepts.html#cb7-1" tabindex="-1"></a><span class="co"># summarise the length of newborn babies</span></span>
<span id="cb7-2"><a href="stat-concepts.html#cb7-2" tabindex="-1"></a><span class="fu">summary</span>(births<span class="sc">$</span>length)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##    35.0    50.0    52.0    51.7    53.0    60.0       3</code></pre>
<p>summary() is a generic function that behaves differently depending on the type of input. With numerical input, it returns a table displaying the minimum and maximum values, the three quartiles (1st, Median, 3rd), the mean and the number of NA values (if any).</p>
<p>Quartiles are the three values that divide a dataset into four equally sized parts. 25% of the data values fall below the first quartile, 50% fall below the second quartile (median), and 75% fall below the third quartile.</p>
<p>A most useful visualisation of the distribution of continuous data is the histogram:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="stat-concepts.html#cb9-1" tabindex="-1"></a><span class="fu">hist</span>(births<span class="sc">$</span>length)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:stat-hist1"></span>
<img src="_main_files/figure-html/stat-hist1-1.svg" alt="Histogram of birth lengths." width="960" />
<p class="caption">
Figure B.3: Histogram of birth lengths.
</p>
</div>
<p>A histogram groups data into intervals, called bins, and shows how many values fall within each interval. It is similar to a bar chart, but the bars are touching to reflect the fact that the data are continuous.</p>
<p>Note that there are much more to histograms than meets the eye. For a deeper understanding and additional options, read the documentation (<code>?hist</code>).</p>
<div id="centre" class="section level3 hasAnchor" number="26.3.1">
<h3><span class="header-section-number">B.3.1</span> Centre<a href="stat-concepts.html#centre" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The central tendency of a dataset refers to the typical or central value around which the data points cluster. It represents the centre of the distribution. Common measures of central tendency include the mean and the median.</p>
<p>The <strong>mean</strong> is perhaps the better-known of the two. It is calculated by summing all the values and dividing by the total number of values. For example, the mean of the values [1, 2, 3] is (1 + 2 + 3) / 3 = 2.</p>
<p>The <strong>median</strong> – often overlooked but equally important – is the middle value when the data are sorted in order. For example, given the values [2, 1, 3], the median is 2 (remember to sort first). If there is an even number of values, the median is the mean of the two central values; for instance, for [1, 2, 3, 4], the median is 2.5.</p>
<p>In the previous examples, the mean and the median are identical. This occurs when the data are perfectly symmetrical. However, when the data are skewed – that is, spread unevenly on either side of the centre – the mean and median can differ significantly. For example, consider the values [1, 2, 999]. The mean is 334, heavily influenced by the extreme value, whereas the median remains 2, effectively splitting the dataset in halves.</p>
<p>Imagine a playground seesaw with a child and an adult seated at opposite ends. The mean corresponds to the balance point of the seesaw, shifting closer to the heavier adult, reflecting the weighted average of the two positions. In contrast, the median represents the midpoint of the plank itself, simply dividing the seesaw into halves regardless of weight.</p>
<p>The choice between using the mean or the median depends largely on the purpose of the analysis as well as the characteristics of the data distribution.</p>
<p>The mean is useful when we want to consider every value in the dataset and obtain a measure that reflects the overall average, especially when the data are symmetrically distributed without extreme outliers.</p>
<p>On the other hand, the median is often preferred when the data are skewed or contain outliers, as it provides a measure of central tendency that is resistant to extreme values and better represents the “typical” observation in such cases.
In SPC the median is particularly useful for runs analysis with run charts. Because the median reflects the midpoint of the data, there is an equal probability – fifty-fifty – that any individual data point will fall above or below it. This balance is crucial for runs analysis, as it ensures that the number and length of runs (consecutive points above or below the median) can be assessed against expected probabilities under random variation. Consequently, using the median helps accurately detect non-random patterns or shifts in the process regardless of the shape of data.</p>
<p>In our birth lengths data, the mean and the median are nearly identical – 51.7 vs 52.0.</p>
<p>Understanding the shape and spread of the data helps inform which measure will provide the most meaningful summary.</p>
</div>
<div id="shape" class="section level3 hasAnchor" number="26.3.2">
<h3><span class="header-section-number">B.3.2</span> Shape<a href="stat-concepts.html#shape" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The shape of a dataset refers to the overall pattern or distribution of values. Two key features that describe the shape of data are symmetry and modality.</p>
<p><strong>Symmetry</strong> describes how evenly the values are distributed around the centre. In a perfectly symmetrical distribution the left and right sides are mirror images and the mean and the median are identical.</p>
<p>When one side of the distribution extends further than the other, the data are said to be skewed. If the tail extends towards higher values, the distribution is right-skewed (positively skewed), and the mean is greater than the median. If it extends towards lower values, it is left-skewed (negatively skewed), and the mean is less than the median. Examples of data that are often right-skewed include waiting times and income, where most observations cluster around the lower end of the scale, while a few extreme values create a long tail extending towards higher values.</p>
<p>Symmetry is also characterised by the mean and median being approximately centred between the minimum and maximum values.</p>
<p>Because the mean and median of birth length are very close, we may assume that the data are approximately symmetrical. However, neither the mean nor the median is well centred between the minimum and maximum values, suggesting that the distribution may still be slightly skewed or influenced by outliers at one end.</p>
<p>The histogram in Figure <a href="stat-concepts.html#fig:stat-hist1">B.3</a> provides a much clearer and more detailed picture of the shape of the data. The majority of values are symmetrically centred, but a few data points have unusually low values (birth length = 35 cm) suggesting a left-skew. However, these outliers appear unlikely for full-term babies and should be investigated further before proceeding with analysis.</p>
<p><strong>Modality</strong> refers to the number of peaks or modes in a distribution. A unimodal distribution has one clear peak, bimodal has two peaks, and multimodal has more than two. Bi- or multimodal distributions indicate the presence of important subgroups in data that need to be taken into account when analysing data.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="stat-concepts.html#cb10-1" tabindex="-1"></a><span class="fu">hist</span>(reno<span class="sc">$</span>dose)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:stat-hist2"></span>
<img src="_main_files/figure-html/stat-hist2-1.svg" alt="Histogram of radiation doses used for renography." width="960" />
<p class="caption">
Figure B.4: Histogram of radiation doses used for renography.
</p>
</div>
<p>Figure <a href="stat-concepts.html#fig:stat-hist2">B.4</a> shows an example of bimodal data, suggesting the presence of two distinct groups of renography procedures – each likely driven by a different underlying cause that is unknown to us. Before plotting these data – as we did in Chapter <a href="limits.html#limits">7</a> – we should first seek an explanation for the observed pattern and consider stratifying the data according to the underlying procedural strategy.</p>
</div>
<div id="spread" class="section level3 hasAnchor" number="26.3.3">
<h3><span class="header-section-number">B.3.3</span> Spread<a href="stat-concepts.html#spread" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The concept of spread in data is fundamental to SPC, as we have discussed numerous times throughout this book – although the term “spread” itself has not been explicitly introduced until now. Spread refers to the variability or diversity within the data, indicating how much the values differ from each other.</p>
<p>When constructing control limits, we rely on the standard deviation (SD or sigma) of common cause variation as a primary measure of spread. However, standard deviation is not the only useful spread indicator. As demonstrated above, the summary() function provides additional measures that reflect the spread of data.</p>
<p>The range represents the distance between the highest and lowest values in a dataset, while the interquartile range (IQR) captures the spread of the middle 50% of the data — calculated as the difference between the third and first quartiles.</p>
<p>The <strong>range</strong> is easy to understand but has limited usefulness on its own, as it tends to increase with sample size. As the number of observations grows, so does the likelihood of including rare – though not necessarily unusual – values.</p>
<p>The <strong>interquartile range</strong> is a more robust measure of spread and can also offer some insight into the shape of the distribution through the position of the centre relative to the quartiles. However, it becomes unreliable with very small sample sizes. When fewer than five values are present – at the very least – calculating quartiles is effectively meaningless.</p>
<p>A simple, useful and compact alternative to histograms is the box plot, which provides a visual summary of the central tendency and spread of a dataset.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="stat-concepts.html#cb11-1" tabindex="-1"></a><span class="fu">boxplot</span>(births<span class="sc">$</span>length)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:stat-box1"></span>
<img src="_main_files/figure-html/stat-box1-1.svg" alt="Boxplot of birth lengths." width="960" />
<p class="caption">
Figure B.5: Boxplot of birth lengths.
</p>
</div>
<p>The box in a box plot represents the interquartile range (IQR), while the line inside the box indicates the median. The whiskers extend from either end of the box to the smallest and largest values that lie within 1.5 times the IQR from the quartiles. Any dots beyond the whiskers represent more extreme values – often referred to as outliers, though there is often nothing truly outlandish about them.</p>
<p>As long as data have a unimodal shape, the box plot is a very effective visualisation of both the centre, shape and spread of a distribution.</p>
<p>Box plots are especially useful with grouped data like in Figure <a href="stat-concepts.html#fig:stat-box2">B.6</a>, which compares the birth length of boys and girls, suggesting that, on average, boys are slightly longer than girls.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="stat-concepts.html#cb12-1" tabindex="-1"></a><span class="fu">boxplot</span>(length <span class="sc">~</span> sex, births)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:stat-box2"></span>
<img src="_main_files/figure-html/stat-box2-1.svg" alt="Stratified boxplot." width="960" />
<p class="caption">
Figure B.6: Stratified boxplot.
</p>
</div>
<p>The <strong>standard deviation</strong> is perhaps the most commonly used measure of spread in a dataset. It tells, on average, how far from the mean each data value lies.</p>
<p>To calculate SD we use</p>
<p><span class="math display">\[
SD = \sqrt{\frac{\sum_{i=1}^{n}(x_i-\bar{x})^2}{n-1}}
\]</span></p>
<p>That is, the square root of the sum of squared deviations from the mean divided by one less than the number of values.</p>
<p>SD can always be calculated, but its usefulness depends on the underlying distribution of the data. This is why we first introduced the range and interquartile range, which are always reliable measures of spread regardless of distribution.</p>
<p>When data follow a Gaussian (or normal) distribution – which we will talk more about in the next section – the standard deviation has some particularly useful properties:</p>
<p>Approximately</p>
<ul>
<li>68% of data values fall within ±1 SD of the mean,</li>
<li>95% fall within ±2 SD, and</li>
<li>99.7% fall within ±3 SD.</li>
</ul>
<p>The first two rules depend heavily on data’s underlying distribution. However, the third rule – that “most” data points fall within ±3 SD – holds true for many common distributions. Without delving into technical details, it can be shown that for any unimodal distribution, at least 95% of the data lie within three standard deviations of the mean. For many common unimodal distributions, especially those that are roughly symmetric, this proportion can rise to more than 98%.</p>
<p>This fact justifies the use of three-sigma limits in SPC charts regardless of the distribution of data and cautions against adopting tighter limits solely to increase sensitivity.</p>
</div>
</div>
<div id="theoretical-distributions" class="section level2 hasAnchor" number="26.4">
<h2><span class="header-section-number">B.4</span> Theoretical distributions<a href="stat-concepts.html#theoretical-distributions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li>Gaussian (normal)</li>
<li>Poisson</li>
<li>Binomial</li>
</ul>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="data-sets.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="diagnostics.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
